#:schema https://starship.rs/config-schema.json

format = '''
[╭](grey)$directory $bun$c $fill $cmd_duration${env_var.IN_NIX_SHELL}
[╰](grey)${env_var.IN_USE_SHELL}$character
'''

[directory]
truncation_length = 8
truncate_to_repo = true
truncation_symbol = " "
format = " $path"

[character]
success_symbol = "[❯](green) "
error_symbol = "[❯](bold red) "

[env_var.IN_NIX_SHELL]
format = '[\[DEV\]](purple)'

[env_var.IN_USE_SHELL]
format = '[\[USE\]](blue)'

[fill]
symbol = " "
